My profile no orders
sergioaok/Ordering-UI pull request #103
Opened 2020-10-21 21:09 UTC by YisusJe

![no orders](https://user-images.githubusercontent.com/50583541/96787151-47d8bd80-13bf-11eb-8341-76ecd708899c.png)

### profile 
#### without changes 
![button](https://user-images.githubusercontent.com/50583541/96787233-65a62280-13bf-11eb-9cae-4c25dad5b594.png)
#### with changes
![update](https://user-images.githubusercontent.com/50583541/96787628-13b1cc80-13c0-11eb-8c4c-18fa4a7b06be.png)

2020-10-22 13:44 UTC, quirozcarlos requested changes

2020-10-22 13:44 UTC, quirozcarlos commented on src/components/UserProfileForm/index.js
> +  console.log(formState.changes)
delete console.log

2020-10-23 15:35 UTC, quirozcarlos commented
@YisusJe native scroll doesn't appers
![image](https://user-images.githubusercontent.com/20915036/97023703-e1b97b00-1523-11eb-9145-69f5a323aa1e.png)

2020-10-28 01:53 UTC, quirozcarlos commented
@YisusJe Pls improve responsive design

![image](https://user-images.githubusercontent.com/20915036/97381083-b7a6e680-189e-11eb-8c83-703d51644816.png)
![image](https://user-images.githubusercontent.com/20915036/97381094-bd043100-189e-11eb-9afd-839d836119cb.png)

Breckpoints: 

320px — 480px: Mobile devices
481px — 768px: iPads, Tablets
769px — 1024px: Small screens, laptops
1025px — 1200px: Desktops, large screens
1201px and more — Extra large screens, TV

2020-10-28 23:26 UTC, quirozcarlos commented
@YisusJe mira los espacios a los borders
![image](https://user-images.githubusercontent.com/20915036/97507350-673d9080-1953-11eb-88bf-1c06aef4f021.png)
![image](https://user-images.githubusercontent.com/20915036/97507390-7fadab00-1953-11eb-9b37-7643dd5f64c1.png)

2020-10-29 04:57 UTC, YisusJe commented
No entiendo el nuevo cambio que debo hacer

2020-10-29 13:34 UTC, quirozcarlos commented
> @quirozcarlos No entiendo el nuevo cambio que debo hacer

Colocarme un poco de padding a los lados que está muy al borde

2020-10-29 21:27 UTC, quirozcarlos commented
Nice!

2020-10-29 21:27 UTC, merged